### PR TITLE
Adding server.inspect to list decorated framework interfaces

### PR DESCRIPTION
**Pull request by gordysc**
Addresses enhancement request: https://github.com/hapijs/hapi/issues/3408

### CODE REVIEW

**Comment by gordysc** [comment]
[coverage.pdf](https://github.com/hapijs/hapi/files/658558/coverage.pdf)

**Comment by hueniverse** [comment]
I prefer this was much simpler. `server.decorations` as a property. Since you cannot un-decorate, keeping such a public property up to date should be trivial.

**Comment by gordysc** [comment]
Agreed, will revisit this approach.

**Comment by gordysc** [comment]
@hueniverse just for clarification, are you suggesting:
```
server.decorations
request.decorations
reply.decorations
```

Or
```
server.decorations = {
  server: <decorations>,
  request: <decorations>,
  reply: <decorations>
}
```

**Comment by devinivy** [comment]
The latter makes more sense to me.

**Comment by AdriVanHoudt** [comment]
@devinivy any particular reason why?

**Comment by devinivy** [comment]
Yes– it's hard to get a hold of a request object or reply interface simply to check if they're decorated with a specific method.  Decorations are added at plugin-registration time, so I think they should be able to be introspected at plugin registration time as well.

**Comment by AdriVanHoudt** [comment]
Ok I agree. Why not both? if you want to check on request you'd have to go `request.server.decorations.request[]` :P

**Comment by hueniverse** [comment]
Just `server.decorations`.

**Comment by devinivy** [comment]
@AdriVanHoudt I would omit that for the express purpose of keeping the features of the API independent of each other.  Plus, if you already have a `request` object you can just check for the decorated method directly on it!

**Comment by gordysc** [comment]
@hueniverse is this approach more inline?

**Comment by hueniverse** [comment]
I'll review it in a week or two.

**Pull request merged**
