### PR TITLE
Prefer user added encoding over built-in

### PR DESCRIPTION
**Pull request by benib**
This implements #3701 and resolves https://github.com/hapijs/discuss/issues/589

Please let me know if I missed anything. And thanks a lot for the great framework ❤️

### CODE REVIEW

**Comment by kanongil** [comment]
Thanks, can you add a test as well?

**Comment by benib** [comment]
@kanongil i changed the existing test to test if the added encoder is preferred over built in ones by sending `accept-encoding: gzip, deflate, test` instead of `accept-encoding: test`.

Would you prefer to have a separate test instead?

**Comment by kanongil** [comment]
Should be fine. The important part is that it would fail with the old code.

**Comment by hueniverse** [comment]
I consider this a bug fix since the only reason to add a custom encoder is to give it higher priority. But also marked it as breaking as it does change existing behavior.

**Pull request merged**
