### PR TITLE
clean up lint

### PR DESCRIPTION
**Pull request by nlf**
after https://github.com/cjihrig/hapi-scope-start/pull/1 is merged this will clean up all the remaining linter warnings

### CODE REVIEW

**Comment by Marsup** [comment]
Why aren't you also setting the lab options to enforce it in the same PR ?

**Comment by nlf** [comment]
It's already set, isn't it?

**Comment by Marsup** [comment]
Nope.

**Comment by nlf** [comment]
What's missing, I thought it was just the `-L` flag?

**Comment by Marsup** [comment]
--lint-errors-threshold and --lint-warnings-threshold. Probably want to set it to 0.

**Comment by Marsup** [comment]
Why's that makefile still here btw ? :)

**Comment by nlf** [comment]
good question :) if there are no objections i can remove it in this PR also

**Comment by Marsup** [comment]
Not without adding the equivalent commands in the npm scripts.

**Comment by Marsup** [comment]
Wow, it seems there's a LOT of work to do on linting, good luck !

**Pull request merged**
