### PR TITLE
Fix several request.url property issues on setUrl()

### PR DESCRIPTION
**Pull request by kanongil**
This PR fixes this following issues in the `request.setUrl()` method:

 * The passed url object is not cloned.
 * Trailing slash stripping should be done after normalization (important if hapijs/call#29 is implemented).
 * Always update pathname derived url properties when path is modified.

This should make for a safer and more consistent `request.setUrl()` experience.

### CODE REVIEW

**Comment by kanongil** [comment]
I added another commit to fix the issues in #3430.

**Comment by hueniverse** [comment]
Why are you preserving the port number when the new host doesn't have one?

**Comment by kanongil** [comment]
I'm not sure. It must have seemed sensible at the time, but using the default port for the scheme also makes sense. This way it is more similar to a redirect.

**Comment by hueniverse** [comment]
If you are going to provide a new full URI, it should override everything including the port.

**Comment by kanongil** [comment]
Ok, I have rebased and revised the info update.

**Pull request merged**
