### PR TITLE
Add preload flag to HSTS header and fix casing for includeSubDomains.

### PR DESCRIPTION
**Pull request by analytically**
See https://scotthelme.co.uk/hsts-preloading/ for more information.

Also fixes casing issue in HSTS header: includeSubDomains - http://tools.ietf.org/html/rfc6797.

### CODE REVIEW

**Comment by devinivy** [comment]
I can't say for sure whether or not this will be an accepted feature, but the PR will likely need to adjust the casing of `includeSubDomains` vs `includeSubdomains` in the tests and include a test for the new option to be considered.  Additionally, the options schema would need to be adjusted around here: https://github.com/hapijs/hapi/blob/master/lib/schema.js#L116.  It does seem like the casing of `includeSubDomains` in this PR is preferred, based upon other examples on the web.

**Comment by hueniverse** [comment]
@nlf?

**Comment by nlf** [comment]
this gets a +1 from me, looks good

**Comment by devinivy** [comment]
Is this our first case of releasing a feature to 10.x and hapi-tls?

**Pull request merged**
