### PR TITLE
fixed teamwork version

### PR DESCRIPTION
**Pull request by irshad437**
This was using a deprecated version of teamwork which was leaving it unable to use. I've updated the version.

### CODE REVIEW

**Comment by cjihrig** [comment]
@irshad437 sorry, but this has a conflict. Would you mind resolving that so that your change can land and be released in hapi v20?

**Comment by irshad437** [comment]
Hi @cjihrig , I had resolved the conflicts but the build fails. I am unable to understand the reason. Could you please help me here?

**Comment by kanongil** [comment]
It seems to be unrelated, as a restart of the test https://travis-ci.org/github/hapijs/hapi/jobs/716867430 cleared the issue.

**Comment by cjihrig** [comment]
Thanks for the contribution!

**Pull request merged**
