### PR TITLE
Bind Promise's callbacks to current domain if set.

### PR DESCRIPTION
**Pull request by rmedaer**
This prevent crashing when server method returning a Promise with callback option set to false and a route handler throw an error.

How to reproduce ?
```js
const Hapi = require('hapi');

var server = new Hapi.Server();

server.connection({
    port: 3000
});


server.method('method', () => Promise.resolve(), { callback: false })

server.route({
    method: 'GET',
    path: '/test',
    config: {
        pre: [
            { method: 'method()' },
        ]
    },
    handler: function(request, reply){
        throw new Error('Oops');
    }
});

server.start(() => {
    console.log('Server listening ...')
})
```

### CODE REVIEW

**Comment by rmedaer** [comment]
Still have to fix linting and tests ... ;-)

**Comment by rmedaer** [comment]
Ok so I'll need you help !

Because the error is Node's internal between promises and domains I'm not able to write tests with inject method and so on...

Could you help me with this ?


```js 
    it('registers a method returning promise with no callback and a route throwing error', (done) => {

        const add = function () {

            return new Promise((resolve, reject) => {

                return resolve();
            });
        };

        const server = new Hapi.Server();
        server.connection();
        server.method('add', add, { callback: false });

        server.route({
            method: 'GET',
            path: '/test',
            config: {
                pre: [
                    'add()'
                ],
                handler: function (request, reply) {

                    throw new Error('Oops');
                }
            }
        });

        server.inject('/test', (res) => {

            expect(res.statusCode).to.equal(500);
            done();
        });
    });
```

**Comment by hueniverse** [comment]
@Marsup Is this still needed?

**Comment by Marsup** [comment]
It looks like the same case as #3202, maybe @rmedaer can confirm it's fixed ?

**Comment by rmedaer** [comment]
@Marsup it was the same issue then #3203 . I'll test and confirm it's fixed ASAP...

**Pull request closed without merging**
