### PR TITLE
Update 2 failing unit tests

### PR DESCRIPTION
**Pull request by neenhouse**
No ticket created for this PR.  This is a simple update to fix 2 failing unit tests on master.  Something must have changed recently because I see valid builds at recent as 8 days ago.

### CODE REVIEW

**Comment by neenhouse** [comment]
I got the failed unit test addressed, but now `The following leaks were detected:FinalizationRegistry, WeakRef` occurs.

**Comment by cjihrig** [comment]
Where are you seeing these failures on master, and how does this fix them?

> I got the failed unit test addressed, but now The following leaks were detected:FinalizationRegistry, WeakRef occurs (not observed locally on nodeJS 12 or 14).

Node releases v14.6.0, which introduced new global variables. Previously, `lab` didn't know about them, so it reported errors. `lab` has already been updated - travis is just using a cached version.

**Comment by neenhouse** [comment]
Observed on last master commit: https://travis-ci.org/github/hapijs/hapi/jobs/709295103

On my branch, I consistently get that error + 1 identical one.  In the unit test, the started server never receives a request an address that is like `http://{HOSTNAME}:60962` but `http://localhost:60962` seems to get around the issue.

**Comment by neenhouse** [comment]
Ok.  I just checked my branch, and now I am only getting the leak errors, the timeouts have disappeared: https://travis-ci.org/github/hapijs/hapi/jobs/711594775.  Something must have changed recently.  But here is a screenshot locally of the failure:

Screen Shot 2020-07-24 at 4 39 13 PM

Going to try reinstalling my modules to see if problem persists.  If not, I'll close this PR.

**Comment by neenhouse** [comment]
Issue was my VPN connection was interfering with host resolution in the unit test.  Sorry for the overhead, going to close this one down.

Screen Shot 2020-07-24 at 4 44 43 PM

**Pull request closed without merging**
