### PR TITLE
Upgrade lab and use shuffle option

### PR DESCRIPTION
**Pull request by geek**
* More hapi lint rules 
* Better code coverage detection

### CODE REVIEW

**Comment by hueniverse** [comment]
Does shuffle keep the test id consistent so -i works?

**Comment by geek** [comment]
@hueniverse Not yet... I will work on fixing this so that the number is retained. At the moment, shuffle is valuable for travis runs more than local test runs with `-i`.

**Comment by hueniverse** [comment]
Yeah, I use npm test all the time and then I call lab -i to repeat issues so this will break it for me.

**Comment by geek** [comment]
@hueniverse fixed

**Pull request merged**
