### PR TITLE
Fix tests for node@16 error format change

### LINKED ISSUE #4282: Adapt tests to support V8 9.3
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v16.9.0
* *module version*: 20.1.5
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): CITGM
* *any other relevant information*: 

#### What problem are you trying to solve?

Run tests with Node.js 16.9.0 (https://github.com/nodejs/node/pull/40011).

Two of them fail because V8 changed the error message when trying to read properties from `null` or `undefined`.

```
   103) Core _debug() outputs 500 on ext exception:
       actual expected
       "Cannot read propertiesproperty 'here' of null (reading 'here')"
       Expected "Cannot read properties of null (reading 'here')" to equal specified value: "Cannot read property 'here' of null"
       at /home/iojs/tmp/citgm_tmp/08e39eff-f7ef-4ead-92fa-cc5d18384c97/@hapi/hapi/test/core.js:338:44
   231) handler execute() returns 500 on handler exception (next tick await):
       actual expected
       "Cannot read propertiesproperty 'here' of null (reading 'here')"
       Expected "Cannot read properties of null (reading 'here')" to equal specified value: "Cannot read property 'here' of null"
       at /home/iojs/tmp/citgm_tmp/08e39eff-f7ef-4ead-92fa-cc5d18384c97/@hapi/hapi/test/handler.js:76:44
```

https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/2754/nodes=fedora-latest-x64/testReport/junit/(root)/citgm/_hapi_hapi_v20_1_5/

#### Do you have a new or modified API suggestion to solve the problem?

Adapt the following assertions to support the new error message:

https://github.com/hapijs/hapi/blob/c2107e9bc9c522c3778e90a3629a0c84f776f9fe/test/handler.js#L65
https://github.com/hapijs/hapi/blob/c2107e9bc9c522c3778e90a3629a0c84f776f9fe/test/core.js#L338

### PR DESCRIPTION
**Pull request by Nargonath**
Closes #4282.

### CODE REVIEW

**Comment by Nargonath** [comment]
Forgot I had to keep the old message format for node < 16 😅

**Comment by devinivy** [comment]
This update to V8 occurred in [node v16.9.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#2021-09-07-version-1690-current-targos).  Could/should we check for node >= v16.9.0 rather than >= v16, even if just to to help keep this precisely documented?

Another option is to base the check on the version of V8 `process.versions.v8`.  V8 doesn't follow semver, but the first two numbers reflect the chromium milestone divided by 10 (e.g. chromium M93 <-> v8 9.3), so a comparison like this should work:

```js
const toChromiumMilestone = (ver) => parseInt(ver.split('.').slice(0, 2).join(''), 10);

toChromiumMilestone(process.versions.v8) >= 93
```

**Comment by Nargonath** [comment]
Yes you're right @devinivy. I'll make the test more precise.

FWIW I prefer to test against the node version than `v8`. It makes it more easily understandable to others IMO.

**Review by kanongil — COMMENTED** [review]
This seems a bit over-engineered. I would just change the test to:

```js
expect(event.error.message).to.include('Cannot read prop');
```

**Comment by Nargonath** [comment]
@kanongil The only problem I see with testing that way is that it could shadow a similar error for another field which might not be the problem we want to test here. It's probably unlikely though.

**Comment by kanongil** [comment]
I know my suggestion is not perfect, but I still think it is a better solution due to the simplicity.

**Comment by cjihrig** [comment]
> The only problem I see with testing that way is that it could shadow a similar error for another field

You could add a second assertion for the field name.

**Comment by Nargonath** [comment]
> You could add a second assertion for the field name.

Yes I was just about to say it, you beat me to it.

> I know my suggestion is not perfect, but I still think it is a better solution due to the simplicity.

I like your suggestion @kanongil, I'll do it that way and assert on the field name also.

**Review by kanongil — APPROVED** [review]
👍

**Pull request merged**
