### PR TITLE
Fix for #2427

### PR DESCRIPTION
**Pull request by kanongil**
This includes a new test that fails on all version of node.

I'm not entirely sure that the fix I have implemented is the best way to handle this issue but it seems to do the trick without messing up any other tests.

### CODE REVIEW

**Comment by hueniverse** [comment]
Removing the fix does not break the test.

**Comment by kanongil** [comment]
@hueniverse Are you sure? I just checked on master and it still fails for me.

FYI, I'm on node v0.10.36 on Yosemite.

**Comment by kanongil** [comment]
@hueniverse I can see you have made your own fix, which is probably wise. However it has issues on node 0.10 as seen in this travis log: https://travis-ci.org/hapijs/hapi/jobs/53393303

It seems your fix requires streams3 for full support.

**Comment by hueniverse** [comment]
@kanongil yeah, I need to find a way around that to first drain the stream. Have been busy with other stuff.

**Pull request merged**
