### PR TITLE
doc: remove cjihrig from the TSC

### PR DESCRIPTION
**Pull request by cjihrig**

### CODE REVIEW

**Comment by geek** [comment]
Thank you for your service.

**Comment by lloydbenson** [comment]
Thanks for all the help @cjihrig!

**Comment by Nargonath** [comment]
It's sad to see you go @cjihrig but thanks for everything you've done.

**Comment by devinivy** [comment]
Can only echo the above: it's sad to see you off but very grateful for all your work 💞 Certainly hope to see you around the hapiverse, and you know... the real world too.

**Comment by shawn-yee** [comment]
OMG~

**Pull request merged**
