### PR TITLE
Add docs on sameSite having some browser support, need for CSRF token…

### PR DESCRIPTION
**Pull request by AJamesPhillips**
…, option behaviour

Do people think this is a) useful to add and b) correct (I sure hope it is but one always needs to triple check with security).

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
useful yes, correct, not sure

**Comment by AJamesPhillips** [comment]
The only other thing is that the other options are not explained in detail so perhaps this one should not be either and people should just do their own research on this issue... though I'd like to think that hapi aims to be the most secure of all web applications which includes the education of its new (and existing?) users.

**Comment by AdriVanHoudt** [comment]
I think it is better -> linking to the official docs should be required though ^^

**Comment by hueniverse** [comment]
I actually rather the docs be less useful here. This is a complicated security option and I don't want people to learn about it from the hapi docs. A simple link to the spec is enough. I don't want to explain the options or give guidance.

**Pull request merged**
