### PR TITLE
removed the legacy reference that was not working

### PR DESCRIPTION
**Pull request by yuukiii**
Removed the joi-legacy dependency.

### CODE REVIEW

**Comment by hueniverse** [comment]
It's a dev dep that is working fine for me.

**Comment by yuukiii** [comment]
You may need to download a fresh branch to see the issue.  I forked and will get updates until this is fixed.

**Comment by hueniverse** [comment]
Why do you care about dev deps?

**Comment by Marsup** [comment]
I don't see any issue either.

**Pull request closed without merging**
